### ISSUE TITLE
"no 'dim names' attribute for array" Issue with CSS on ATAC assay #12 Open

### ISSUE THREAD

**Issue by yojetsharma** [quadbio/scMultiome_analysis_vignette#3]
Posting from: https://github.com/quadbio/simspec/issues/12#issue-2164801335 
I am following the scmultiome tutorial (https://github.com/quadbio/scMultiome_analysis_vignette/blob/main/Tutorial.md#step-45-data-integration-of-the-atac-assay) and I have a list of 4-multiome files which are merged and everything runs fine except when I reach ATAC assay section:

```
> seurat
An object of class Seurat 
384283 features across 37917 samples within 2 assays 
Active assay: ATAC (347682 features, 346480 variable features)
 1 other assay present: RNA
 6 dimensional reductions calculated: lsi, umap_atac, pca, umap_rna, css_rna, umap_css_rna
> library(simspec)
> seurat <- cluster_sim_spectrum(seurat,
+                                label_tag = "orig.ident",
+                                use_dr = "lsi",
+                                dims_use = 2:30,
+                                cluster_resolution = 0.6,
+                                reduction.name = "css_atac",
+                                reduction.key = "CSSATAC_")
Error in object[[object@active.assay]]@scale.data[var_genes, ] : 
  no 'dimnames' attribute for array
```

**Comment by zhisonghe** [comment]
It is a bug recently introduced which performs an unnecessary subset of the scale.data matrix. This is usually not an issue for RNA assay but for the ATAC assay it is fatal as the scaled data matrix is usually empty. An update has just been pushed to fix this issue.
